# Test 2 

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, v1.test_vtol ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH_NAMEX: ${GITHUB_REF##*/}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     
      - name: Print BRANCH_NAMEX ENV
        run: echo BRANCH_NAMEX ENV of ${{ env.BRANCH_NAMEX }}
      - name: Print BRANCH_NAMEX ENV QUOTED
        run: echo "BRANCH_NAMEX ENV of ${{ env.BRANCH_NAMEX }}"
        
      # Print branch name
      - name: Branch name string
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Branch name string quoted
        run: echo "running on branch ${GITHUB_REF##*/}"
        
      - name: Dump github ref
        env:
          MY_GH_REF: ${{ github.ref }}
        run: echo "$MY_GH_REF"
      - name: Dump github base_ref
        env:
          MY_GH_BASE_REF: ${{ github.base_ref }}
        run: echo "$MY_GH_BASE_REF"
      - name: Dump github head_ref
        env:
          MY_GH_HEAD_REF: ${{ github.head_ref }}
        run: echo "$MY_GH_HEAD_REF"

      - name: Dump GITHUB_REF
        run: echo "$GITHUB_REF"
      - name: Dump GITHUB_HEAD_REF
        run: echo "$GITHUB_HEAD_REF"
      - name: Dump github GITHUB_BASE_REF
        run: echo "$GITHUB_BASE_REF"
        
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: Debug
        run: echo ${{ env.BRANCH_NAME }} 
      - name: Debug quoted
        run: echo "${{ env.BRANCH_NAME }}"
        

